# wrangler.toml
name = "mastra-hono-hello-world"
main = "src/app.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Observability configuration
[observability]
enabled = true
# Optional: specify head sampling rate (0.0 to 1.0)
head_sampling_rate = 1.0

[vars]
LOG_LEVEL="debug"
DEBUG="*"
